# Site settings
url: "//localhost:4000"
author: "BlinkTrade"
baseurl: ""
deploy_version: "HEAD"

exchange: "romaniabex"
exchange_logo: "romaniabex"

default_country_code: "RO"
blinktrade_broker_id: 10

blinktrade_backend_api: "api.testnet.blinktrade.com"
google_analytics_id: "UA-58112377-1"
zopim_key: "2ZQbAVSILzBFbO31Z6EletdDQaW7H9xj"



# Build settings
markdown: kramdown


languages: ["ro", "pt_BR", "en_US", "es"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
