# Site settings
#url: "//localhost:4000"   # activate this to test on your localhost
url: "https://urdubit.com"
author: "BlinkTrade"
baseurl: ""
deploy_version: "HEAD"

exchange: "urdubit"
exchange_logo: "urdubit"

default_country_code: "PK"
blinktrade_broker_id: 8 # 9 is the id for the demo backend. Don't change that if you don't understand what you doing.

blinktrade_backend_api: "api.blinktrade.com"
#blinktrade_backend_api: "api.testnet.blinktrade.com"
#blinktrade_backend_api: "localhost"
google_analytics_id: "UA-55630972-1"
zopim_key: "2cg2Dsyc7IS5tVvP3UgjCrs4SuAuq7NW"


# Build settings
markdown: kramdown


languages: ["en_US", "es", "pt_BR", "ro"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
